//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChooseYourBike.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Advertising11 = new HashSet<Advertising>();
            this.Comments1 = new HashSet<Comments>();
            this.Image2 = new HashSet<Image>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Mark { get; set; }
        public string Model { get; set; }
        public Nullable<int> Category { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<System.DateTime> DateOfBuild { get; set; }
        public Nullable<int> Frame { get; set; }
        public Nullable<int> Fork { get; set; }
        public Nullable<int> Transmission { get; set; }
        public Nullable<int> Shifters { get; set; }
        public Nullable<int> Brakes { get; set; }
        public Nullable<int> Wheels { get; set; }
        public Nullable<int> StrWheel { get; set; }
        public Nullable<int> Saddle { get; set; }
        public Nullable<int> Pedals { get; set; }
        public Nullable<int> Accesories { get; set; }
    
        public virtual Accesories Accesories1 { get; set; }
        public virtual Brakes Brakes1 { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual Fork Fork1 { get; set; }
        public virtual Frame Frame1 { get; set; }
        public virtual Mark Mark1 { get; set; }
        public virtual Pedals Pedals1 { get; set; }
        public virtual Saddle Saddle1 { get; set; }
        public virtual Shifters Shifters1 { get; set; }
        public virtual StrWheel StrWheel1 { get; set; }
        public virtual Transmission Transmission1 { get; set; }
        public virtual Wheels Wheels1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advertising> Advertising11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Image2 { get; set; }
    }
}
